### ISSUE TITLE
Remove node.js files. Create package.json.

### ISSUE THREAD

**Issue by sesm** [Transet/Web-Technologies_site#1]
Don't commit node_modules folder, commit package.json instead.

**Comment by sesm** [comment]
Also, don't commit .project.
Consider using .gitignore to specify, which files to commit and which not.

**Comment by Transet** [comment]
fixed by following commits: https://github.com/Transet/Web-Technologies_site/commit/fb41fcdd8af5ff21f5ed23d2e8acbac1e8a69893 https://github.com/Transet/Web-Technologies_site/commit/391fafd69aebfc188a021e2b5040edd90f1f9036 https://github.com/Transet/Web-Technologies_site/commit/d80dd9e34fb0d51fbfd8b8161a87a4cc37989df8
mark as resolved.
