### ISSUE TITLE
Extra credit: add event throttling for scroll event handler.

### ISSUE THREAD

**Issue by sesm** [Transet/Web-Technologies_site#14]
As you can see, 'scroll' event listener makes page scrolling unresponsive. 
Read about event throttling, add throttling to 'scroll' event handler.
Don't use any libraries.

**Comment by Transet** [comment]
Since we should not use external library, we must write own function.
During testing, I could observe a bug. If we made a fast scroll to down and to top, menu can stuck in the top of header. 
@sesm, Could you confirm this behaviour as valid?
I tried with 10,25,50,100,200ms time and greater, But in all cases I can see this bug.

**Comment by sesm** [comment]
@Transet it's a bug in your implementation. 
You should handle the last event, that arrived during timeout.

**Comment by Transet** [comment]
Mark as resolved.
Makes callback.call() after delay.

**Comment by sesm** [comment]
I still don't think it's complete.
In your particular case, it's important to have both leading and trailing call:
- If you don't have trailing call, you will end up with wrong menu position (as you've already noticed)
- If you don't have leading call, you will always have a delay between scrolling and menu re-positioning. Delay of 100ms is easily noticeable by human eye.

**Comment by Transet** [comment]
In first case, menu should not have the wrong position, because event calls after delay. And I can't reproduce that bug with such implimenation.
In second case, you suggest to create two different option, leading (first time calls imideatly) and trailing(last call should exist). If yes, feel free to reopen issue and I'll get it.

**Comment by sesm** [comment]
I don't suggest to add any options. I just explain, why in your particular case you need both leading and trailing call.

**Comment by Transet** [comment]
Yes, I got it. I added "lastCall" operation. No flickers. No stucks. Decres timeout to 50ms. Seems all is fine. 
Mark as resolved.

**Comment by sesm** [comment]
Just for your information: 50 ms is still easily noticeable by human eye, because it's more than 3 frames at 60 FPS.
I would suggest using 10ms timeout: it's under one frame at 60 FPS, but still long enough to prevent scroll unresponsiveness.

**Comment by Transet** [comment]
fixed
